export const LNK_SEARCH_SCRAP_QUEUE_NAME = process.env.LNK_SEARCH_SCRAP_QUEUE_NAME ?? 'lnkSearchScrapQueue'
export const LNK_JOB_DETAILS_SCRAP_QUEUE_NAME = process.env.LNK_SEARCH_SCRAP_QUEUE_NAME ?? 'lnkJobDetailsScrapQueue'
export const LNK_FLAG_RELEVANT_JOBS_QUEUE_NAME = process.env.LNK_FLAG_RELEVANT_JOBS_QUEUE_NAME ?? 'lnkFlagRelevantJobsQueue'
export const REDIS_HOST = process.env.REDIS_HOST ?? '127.0.0.1'
export const REDIS_PORT = process.env.REDIS_PORT ?? '6379'
